# Generated by Django 4.2.11 on 2024-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_product_quantity_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
