# Generated by Django 4.2.11 on 2024-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_product_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
