# Generated by Django 4.2.11 on 2024-03-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_order_orderdetail_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
