# Generated by Django 4.2.11 on 2024-03-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_discount_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
