# Generated by Django 4.2.11 on 2024-03-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(null=True),
        ),
    ]
