# Generated by Django 4.2.11 on 2024-03-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='percent',
            new_name='money',
        ),
    ]
